// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ActionPacket.proto

#ifndef PROTOBUF_ActionPacket_2eproto__INCLUDED
#define PROTOBUF_ActionPacket_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "WaypointPacket.pb.h"
// @@protoc_insertion_point(includes)

namespace uavforge {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ActionPacket_2eproto();
void protobuf_AssignDesc_ActionPacket_2eproto();
void protobuf_ShutdownFile_ActionPacket_2eproto();

class ActionPacket;

enum ActionPacket_ActionType {
  ActionPacket_ActionType_START = 0,
  ActionPacket_ActionType_REQUEST_INFO = 1,
  ActionPacket_ActionType_ADD_WAYPOINT = 2,
  ActionPacket_ActionType_SET_HOME = 3,
  ActionPacket_ActionType_REMOVE_WAYPOINT = 4,
  ActionPacket_ActionType_STOP = 14,
  ActionPacket_ActionType_SHUTDOWN = 15
};
bool ActionPacket_ActionType_IsValid(int value);
const ActionPacket_ActionType ActionPacket_ActionType_ActionType_MIN = ActionPacket_ActionType_START;
const ActionPacket_ActionType ActionPacket_ActionType_ActionType_MAX = ActionPacket_ActionType_SHUTDOWN;
const int ActionPacket_ActionType_ActionType_ARRAYSIZE = ActionPacket_ActionType_ActionType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ActionPacket_ActionType_descriptor();
inline const ::std::string& ActionPacket_ActionType_Name(ActionPacket_ActionType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ActionPacket_ActionType_descriptor(), value);
}
inline bool ActionPacket_ActionType_Parse(
    const ::std::string& name, ActionPacket_ActionType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ActionPacket_ActionType>(
    ActionPacket_ActionType_descriptor(), name, value);
}
// ===================================================================

class ActionPacket : public ::google::protobuf::Message {
 public:
  ActionPacket();
  virtual ~ActionPacket();

  ActionPacket(const ActionPacket& from);

  inline ActionPacket& operator=(const ActionPacket& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActionPacket& default_instance();

  void Swap(ActionPacket* other);

  // implements Message ----------------------------------------------

  ActionPacket* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ActionPacket& from);
  void MergeFrom(const ActionPacket& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ActionPacket_ActionType ActionType;
  static const ActionType START = ActionPacket_ActionType_START;
  static const ActionType REQUEST_INFO = ActionPacket_ActionType_REQUEST_INFO;
  static const ActionType ADD_WAYPOINT = ActionPacket_ActionType_ADD_WAYPOINT;
  static const ActionType SET_HOME = ActionPacket_ActionType_SET_HOME;
  static const ActionType REMOVE_WAYPOINT = ActionPacket_ActionType_REMOVE_WAYPOINT;
  static const ActionType STOP = ActionPacket_ActionType_STOP;
  static const ActionType SHUTDOWN = ActionPacket_ActionType_SHUTDOWN;
  static inline bool ActionType_IsValid(int value) {
    return ActionPacket_ActionType_IsValid(value);
  }
  static const ActionType ActionType_MIN =
    ActionPacket_ActionType_ActionType_MIN;
  static const ActionType ActionType_MAX =
    ActionPacket_ActionType_ActionType_MAX;
  static const int ActionType_ARRAYSIZE =
    ActionPacket_ActionType_ActionType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ActionType_descriptor() {
    return ActionPacket_ActionType_descriptor();
  }
  static inline const ::std::string& ActionType_Name(ActionType value) {
    return ActionPacket_ActionType_Name(value);
  }
  static inline bool ActionType_Parse(const ::std::string& name,
      ActionType* value) {
    return ActionPacket_ActionType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required int32 priority = 1;
  inline bool has_priority() const;
  inline void clear_priority();
  static const int kPriorityFieldNumber = 1;
  inline ::google::protobuf::int32 priority() const;
  inline void set_priority(::google::protobuf::int32 value);

  // required .uavforge.ActionPacket.ActionType action_type = 2;
  inline bool has_action_type() const;
  inline void clear_action_type();
  static const int kActionTypeFieldNumber = 2;
  inline ::uavforge::ActionPacket_ActionType action_type() const;
  inline void set_action_type(::uavforge::ActionPacket_ActionType value);

  // repeated .uavforge.WaypointPacket waypoints = 3;
  inline int waypoints_size() const;
  inline void clear_waypoints();
  static const int kWaypointsFieldNumber = 3;
  inline const ::uavforge::WaypointPacket& waypoints(int index) const;
  inline ::uavforge::WaypointPacket* mutable_waypoints(int index);
  inline ::uavforge::WaypointPacket* add_waypoints();
  inline const ::google::protobuf::RepeatedPtrField< ::uavforge::WaypointPacket >&
      waypoints() const;
  inline ::google::protobuf::RepeatedPtrField< ::uavforge::WaypointPacket >*
      mutable_waypoints();

  // @@protoc_insertion_point(class_scope:uavforge.ActionPacket)
 private:
  inline void set_has_priority();
  inline void clear_has_priority();
  inline void set_has_action_type();
  inline void clear_has_action_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 priority_;
  int action_type_;
  ::google::protobuf::RepeatedPtrField< ::uavforge::WaypointPacket > waypoints_;
  friend void  protobuf_AddDesc_ActionPacket_2eproto();
  friend void protobuf_AssignDesc_ActionPacket_2eproto();
  friend void protobuf_ShutdownFile_ActionPacket_2eproto();

  void InitAsDefaultInstance();
  static ActionPacket* default_instance_;
};
// ===================================================================


// ===================================================================

// ActionPacket

// required int32 priority = 1;
inline bool ActionPacket::has_priority() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ActionPacket::set_has_priority() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ActionPacket::clear_has_priority() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ActionPacket::clear_priority() {
  priority_ = 0;
  clear_has_priority();
}
inline ::google::protobuf::int32 ActionPacket::priority() const {
  // @@protoc_insertion_point(field_get:uavforge.ActionPacket.priority)
  return priority_;
}
inline void ActionPacket::set_priority(::google::protobuf::int32 value) {
  set_has_priority();
  priority_ = value;
  // @@protoc_insertion_point(field_set:uavforge.ActionPacket.priority)
}

// required .uavforge.ActionPacket.ActionType action_type = 2;
inline bool ActionPacket::has_action_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ActionPacket::set_has_action_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ActionPacket::clear_has_action_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ActionPacket::clear_action_type() {
  action_type_ = 0;
  clear_has_action_type();
}
inline ::uavforge::ActionPacket_ActionType ActionPacket::action_type() const {
  // @@protoc_insertion_point(field_get:uavforge.ActionPacket.action_type)
  return static_cast< ::uavforge::ActionPacket_ActionType >(action_type_);
}
inline void ActionPacket::set_action_type(::uavforge::ActionPacket_ActionType value) {
  assert(::uavforge::ActionPacket_ActionType_IsValid(value));
  set_has_action_type();
  action_type_ = value;
  // @@protoc_insertion_point(field_set:uavforge.ActionPacket.action_type)
}

// repeated .uavforge.WaypointPacket waypoints = 3;
inline int ActionPacket::waypoints_size() const {
  return waypoints_.size();
}
inline void ActionPacket::clear_waypoints() {
  waypoints_.Clear();
}
inline const ::uavforge::WaypointPacket& ActionPacket::waypoints(int index) const {
  // @@protoc_insertion_point(field_get:uavforge.ActionPacket.waypoints)
  return waypoints_.Get(index);
}
inline ::uavforge::WaypointPacket* ActionPacket::mutable_waypoints(int index) {
  // @@protoc_insertion_point(field_mutable:uavforge.ActionPacket.waypoints)
  return waypoints_.Mutable(index);
}
inline ::uavforge::WaypointPacket* ActionPacket::add_waypoints() {
  // @@protoc_insertion_point(field_add:uavforge.ActionPacket.waypoints)
  return waypoints_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::uavforge::WaypointPacket >&
ActionPacket::waypoints() const {
  // @@protoc_insertion_point(field_list:uavforge.ActionPacket.waypoints)
  return waypoints_;
}
inline ::google::protobuf::RepeatedPtrField< ::uavforge::WaypointPacket >*
ActionPacket::mutable_waypoints() {
  // @@protoc_insertion_point(field_mutable_list:uavforge.ActionPacket.waypoints)
  return &waypoints_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace uavforge

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::uavforge::ActionPacket_ActionType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::uavforge::ActionPacket_ActionType>() {
  return ::uavforge::ActionPacket_ActionType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ActionPacket_2eproto__INCLUDED
