// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WaypointPacket.proto

#ifndef PROTOBUF_WaypointPacket_2eproto__INCLUDED
#define PROTOBUF_WaypointPacket_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace uavforge {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_WaypointPacket_2eproto();
void protobuf_AssignDesc_WaypointPacket_2eproto();
void protobuf_ShutdownFile_WaypointPacket_2eproto();

class WaypointPacket;

// ===================================================================

class WaypointPacket : public ::google::protobuf::Message {
 public:
  WaypointPacket();
  virtual ~WaypointPacket();

  WaypointPacket(const WaypointPacket& from);

  inline WaypointPacket& operator=(const WaypointPacket& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WaypointPacket& default_instance();

  void Swap(WaypointPacket* other);

  // implements Message ----------------------------------------------

  WaypointPacket* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WaypointPacket& from);
  void MergeFrom(const WaypointPacket& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 seqNo = 1;
  inline bool has_seqno() const;
  inline void clear_seqno();
  static const int kSeqNoFieldNumber = 1;
  inline ::google::protobuf::int32 seqno() const;
  inline void set_seqno(::google::protobuf::int32 value);

  // required double lat = 2;
  inline bool has_lat() const;
  inline void clear_lat();
  static const int kLatFieldNumber = 2;
  inline double lat() const;
  inline void set_lat(double value);

  // required double lng = 3;
  inline bool has_lng() const;
  inline void clear_lng();
  static const int kLngFieldNumber = 3;
  inline double lng() const;
  inline void set_lng(double value);

  // required float alt = 4;
  inline bool has_alt() const;
  inline void clear_alt();
  static const int kAltFieldNumber = 4;
  inline float alt() const;
  inline void set_alt(float value);

  // required float speed = 5;
  inline bool has_speed() const;
  inline void clear_speed();
  static const int kSpeedFieldNumber = 5;
  inline float speed() const;
  inline void set_speed(float value);

  // @@protoc_insertion_point(class_scope:uavforge.WaypointPacket)
 private:
  inline void set_has_seqno();
  inline void clear_has_seqno();
  inline void set_has_lat();
  inline void clear_has_lat();
  inline void set_has_lng();
  inline void clear_has_lng();
  inline void set_has_alt();
  inline void clear_has_alt();
  inline void set_has_speed();
  inline void clear_has_speed();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double lat_;
  ::google::protobuf::int32 seqno_;
  float alt_;
  double lng_;
  float speed_;
  friend void  protobuf_AddDesc_WaypointPacket_2eproto();
  friend void protobuf_AssignDesc_WaypointPacket_2eproto();
  friend void protobuf_ShutdownFile_WaypointPacket_2eproto();

  void InitAsDefaultInstance();
  static WaypointPacket* default_instance_;
};
// ===================================================================


// ===================================================================

// WaypointPacket

// required int32 seqNo = 1;
inline bool WaypointPacket::has_seqno() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WaypointPacket::set_has_seqno() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WaypointPacket::clear_has_seqno() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WaypointPacket::clear_seqno() {
  seqno_ = 0;
  clear_has_seqno();
}
inline ::google::protobuf::int32 WaypointPacket::seqno() const {
  // @@protoc_insertion_point(field_get:uavforge.WaypointPacket.seqNo)
  return seqno_;
}
inline void WaypointPacket::set_seqno(::google::protobuf::int32 value) {
  set_has_seqno();
  seqno_ = value;
  // @@protoc_insertion_point(field_set:uavforge.WaypointPacket.seqNo)
}

// required double lat = 2;
inline bool WaypointPacket::has_lat() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void WaypointPacket::set_has_lat() {
  _has_bits_[0] |= 0x00000002u;
}
inline void WaypointPacket::clear_has_lat() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void WaypointPacket::clear_lat() {
  lat_ = 0;
  clear_has_lat();
}
inline double WaypointPacket::lat() const {
  // @@protoc_insertion_point(field_get:uavforge.WaypointPacket.lat)
  return lat_;
}
inline void WaypointPacket::set_lat(double value) {
  set_has_lat();
  lat_ = value;
  // @@protoc_insertion_point(field_set:uavforge.WaypointPacket.lat)
}

// required double lng = 3;
inline bool WaypointPacket::has_lng() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void WaypointPacket::set_has_lng() {
  _has_bits_[0] |= 0x00000004u;
}
inline void WaypointPacket::clear_has_lng() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void WaypointPacket::clear_lng() {
  lng_ = 0;
  clear_has_lng();
}
inline double WaypointPacket::lng() const {
  // @@protoc_insertion_point(field_get:uavforge.WaypointPacket.lng)
  return lng_;
}
inline void WaypointPacket::set_lng(double value) {
  set_has_lng();
  lng_ = value;
  // @@protoc_insertion_point(field_set:uavforge.WaypointPacket.lng)
}

// required float alt = 4;
inline bool WaypointPacket::has_alt() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void WaypointPacket::set_has_alt() {
  _has_bits_[0] |= 0x00000008u;
}
inline void WaypointPacket::clear_has_alt() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void WaypointPacket::clear_alt() {
  alt_ = 0;
  clear_has_alt();
}
inline float WaypointPacket::alt() const {
  // @@protoc_insertion_point(field_get:uavforge.WaypointPacket.alt)
  return alt_;
}
inline void WaypointPacket::set_alt(float value) {
  set_has_alt();
  alt_ = value;
  // @@protoc_insertion_point(field_set:uavforge.WaypointPacket.alt)
}

// required float speed = 5;
inline bool WaypointPacket::has_speed() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void WaypointPacket::set_has_speed() {
  _has_bits_[0] |= 0x00000010u;
}
inline void WaypointPacket::clear_has_speed() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void WaypointPacket::clear_speed() {
  speed_ = 0;
  clear_has_speed();
}
inline float WaypointPacket::speed() const {
  // @@protoc_insertion_point(field_get:uavforge.WaypointPacket.speed)
  return speed_;
}
inline void WaypointPacket::set_speed(float value) {
  set_has_speed();
  speed_ = value;
  // @@protoc_insertion_point(field_set:uavforge.WaypointPacket.speed)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace uavforge

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_WaypointPacket_2eproto__INCLUDED
