/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.4 at Sun Nov 15 16:49:20 2015. */

#include "Packet.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t uavforge_Packet_fields[9] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, uavforge_Packet, timestamp, timestamp, 0),
    PB_FIELD(  2, STRING  , REQUIRED, CALLBACK, OTHER, uavforge_Packet, sender, timestamp, 0),
    PB_FIELD(  3, STRING  , REQUIRED, CALLBACK, OTHER, uavforge_Packet, target, sender, 0),
    PB_FIELD(  4, UENUM   , REQUIRED, STATIC  , OTHER, uavforge_Packet, type, target, 0),
    PB_ONEOF_FIELD(contents,   5, MESSAGE , ONEOF, STATIC  , OTHER, uavforge_Packet, telem, type, &uavforge_TelemetryPacket_fields),
    PB_ONEOF_FIELD(contents,   6, MESSAGE , ONEOF, STATIC  , OTHER, uavforge_Packet, comm, type, &uavforge_ActionPacket_fields),
    PB_ONEOF_FIELD(contents,   8, MESSAGE , ONEOF, STATIC  , OTHER, uavforge_Packet, info, type, &uavforge_InfoPacket_fields),
    PB_ONEOF_FIELD(contents,   9, MESSAGE , ONEOF, STATIC  , OTHER, uavforge_Packet, ack, type, &uavforge_AckPacket_fields),
    PB_LAST_FIELD
};

const pb_field_t uavforge_TelemetryPacket_fields[13] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, uavforge_TelemetryPacket, seqNo, seqNo, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, uavforge_TelemetryPacket, accx, seqNo, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, uavforge_TelemetryPacket, accy, accx, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, uavforge_TelemetryPacket, accz, accy, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, uavforge_TelemetryPacket, pitch, accz, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, uavforge_TelemetryPacket, roll, pitch, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, uavforge_TelemetryPacket, yaw, roll, 0),
    PB_FIELD(  8, DOUBLE  , REQUIRED, STATIC  , OTHER, uavforge_TelemetryPacket, lat, yaw, 0),
    PB_FIELD(  9, DOUBLE  , REQUIRED, STATIC  , OTHER, uavforge_TelemetryPacket, lng, lat, 0),
    PB_FIELD( 10, FLOAT   , REQUIRED, STATIC  , OTHER, uavforge_TelemetryPacket, alt, lng, 0),
    PB_FIELD( 11, FLOAT   , REQUIRED, STATIC  , OTHER, uavforge_TelemetryPacket, speed, alt, 0),
    PB_FIELD( 12, INT32   , REQUIRED, STATIC  , OTHER, uavforge_TelemetryPacket, barometer, speed, 0),
    PB_LAST_FIELD
};

const pb_field_t uavforge_ActionPacket_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, uavforge_ActionPacket, priority, priority, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, uavforge_ActionPacket, action_type, priority, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, uavforge_ActionPacket, waypoints, action_type, &uavforge_ActionPacket_WaypointPacket_fields),
    PB_LAST_FIELD
};

const pb_field_t uavforge_ActionPacket_WaypointPacket_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, uavforge_ActionPacket_WaypointPacket, seqNo, seqNo, 0),
    PB_FIELD(  2, DOUBLE  , REQUIRED, STATIC  , OTHER, uavforge_ActionPacket_WaypointPacket, lat, seqNo, 0),
    PB_FIELD(  3, DOUBLE  , REQUIRED, STATIC  , OTHER, uavforge_ActionPacket_WaypointPacket, lng, lat, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, uavforge_ActionPacket_WaypointPacket, alt, lng, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, uavforge_ActionPacket_WaypointPacket, speed, alt, 0),
    PB_LAST_FIELD
};

const pb_field_t uavforge_InfoPacket_fields[4] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, uavforge_InfoPacket, pointsStorable, pointsStorable, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, uavforge_InfoPacket, battery, pointsStorable, 0),
    PB_FIELD(  3, STRING  , REPEATED, CALLBACK, OTHER, uavforge_InfoPacket, infoStrings, battery, 0),
    PB_LAST_FIELD
};

const pb_field_t uavforge_AckPacket_fields[2] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, uavforge_AckPacket, ackTimestamp, ackTimestamp, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(uavforge_Packet, contents.telem) < 65536 && pb_membersize(uavforge_ActionPacket, waypoints) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_uavforge_Packet_uavforge_TelemetryPacket_uavforge_ActionPacket_uavforge_ActionPacket_WaypointPacket_uavforge_InfoPacket_uavforge_AckPacket)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(uavforge_Packet, contents.telem) < 256 && pb_membersize(uavforge_ActionPacket, waypoints) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_uavforge_Packet_uavforge_TelemetryPacket_uavforge_ActionPacket_uavforge_ActionPacket_WaypointPacket_uavforge_InfoPacket_uavforge_AckPacket)
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

